apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: node-express
build:
  artifacts:
    - image: node-express
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useDockerCLI: true
manifests:
  rawYaml:
    - deployment.yaml
portForward:
  - resourceType: service
    resourceName: node-express
    port: 3000
